### ISSUE TITLE
can't build on head with go 1.11.4

### ISSUE THREAD

**Issue by ChangePlaces** [muesli/beehive#212]
/root/go/src/github.com/muesli/beehive/api/resources/bees/bees_post.go:63:31: not enough arguments in call to smolder.ErrorResponseHandler
        have (*restful.Request, *restful.Response, *smolder.ErrorResponse)
        want (*restful.Request, *restful.Response, error, *smolder.ErrorResponse)
/root/go/src/github.com/muesli/beehive/api/resources/bees/bees_post.go:63:75: too many arguments in call to smolder.NewErrorResponse
        have (number, bool, error, string)
        want (int, interface {}, string)
# github.com/muesli/beehive/api/resources/chains
/root/go/src/github.com/muesli/beehive/api/resources/chains/chains_post.go:63:31: not enough arguments in call to smolder.ErrorResponseHandler
        have (*restful.Request, *restful.Response, *smolder.ErrorResponse)
        want (*restful.Request, *restful.Response, error, *smolder.ErrorResponse)
/root/go/src/github.com/muesli/beehive/api/resources/chains/chains_post.go:63:75: too many arguments in call to smolder.NewErrorResponse
        have (number, bool, string, string)
        want (int, interface {}, string)

**Comment by rubiojr** [comment]
@ChangePlaces: https://github.com/muesli/beehive/pull/213 is trying to fix this.

**Comment by ChangePlaces** [comment]
Thanks, would love to get this working on my pi!

**Comment by muesli** [comment]
Should be fixed in master now. Note that we switched to Go modules.
